-- MySQL Script generated by MySQL Workbench
-- Tue May  9 12:02:18 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema petcare
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema petcare
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `petcare` DEFAULT CHARACTER SET utf8mb4 ;
USE `petcare` ;

-- -----------------------------------------------------
-- Table `petcare`.`tipousuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petcare`.`tipousuario` (
  `idtipousuario` INT(11) NOT NULL,
  `nombre` VARCHAR(15) NULL DEFAULT NULL,
  PRIMARY KEY (`idtipousuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `petcare`.`administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petcare`.`administrador` (
  `idadministrador` INT(11) NOT NULL,
  `idtipousuario` INT(11) NULL DEFAULT NULL,
  `nombres` VARCHAR(35) NULL DEFAULT NULL,
  `apellidos` VARCHAR(35) NULL DEFAULT NULL,
  `dni` CHAR(8) NULL DEFAULT NULL,
  `telefono` CHAR(9) NULL DEFAULT NULL,
  `direccion` VARCHAR(50) NULL DEFAULT NULL,
  `correo` VARCHAR(45) NULL DEFAULT NULL,
  `pass` VARCHAR(45) NULL DEFAULT NULL,
  `estado` CHAR(1) NULL DEFAULT NULL,
  `tipousuario_idtipousuario` INT(11) NOT NULL,
  PRIMARY KEY (`idadministrador`),
 
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `petcare`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petcare`.`cliente` (
  `idcliente` INT(11) NOT NULL AUTO_INCREMENT,
  `idtipousuario` VARCHAR(45) NULL DEFAULT NULL,
  `nombres` VARCHAR(35) NULL DEFAULT NULL,
  `apellidos` VARCHAR(35) NULL DEFAULT NULL,
  `dni` CHAR(8) NULL DEFAULT NULL,
  `telefono` CHAR(9) NULL DEFAULT NULL,
  `direccion` VARCHAR(50) NULL DEFAULT NULL,
  `correo` VARCHAR(45) NULL DEFAULT NULL,
  `pass` VARCHAR(45) NULL DEFAULT NULL,
  `estado` CHAR(1) NULL DEFAULT NULL,
  `tipousuario_idtipousuario` INT(11) NOT NULL,
  PRIMARY KEY (`idcliente`),
  INDEX `idtipousuario` (`idtipousuario` ASC) VISIBLE,
  INDEX `fk_cliente_tipousuario1_idx` (`tipousuario_idtipousuario` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_tipousuario1`
    FOREIGN KEY (`tipousuario_idtipousuario`)
    REFERENCES `petcare`.`tipousuario` (`idtipousuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '			';


-- -----------------------------------------------------
-- Table `petcare`.`veterinario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petcare`.`veterinario` (
  `idveterinario` INT(11) NOT NULL AUTO_INCREMENT,
  `idtipousuario` INT(11) NULL DEFAULT NULL,
  `nombres` VARCHAR(35) NULL DEFAULT NULL,
  `apellidos` VARCHAR(35) NULL DEFAULT NULL,
  `dni` CHAR(8) NULL DEFAULT NULL,
  `telefono` CHAR(9) NULL DEFAULT NULL,
  `direccion` VARCHAR(50) NULL DEFAULT NULL,
  `correo` VARCHAR(45) NULL DEFAULT NULL,
  `pass` VARCHAR(45) NULL DEFAULT NULL,
  `estado` CHAR(1) NULL DEFAULT NULL,
  PRIMARY KEY (`idveterinario`),
  INDEX `idtipousuario` (`idtipousuario` ASC) VISIBLE,
  CONSTRAINT `veterinario_ibfk_1`
    FOREIGN KEY (`idtipousuario`)
    REFERENCES `petcare`.`tipousuario` (`idtipousuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `petcare`.`horario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petcare`.`horario` (
  `idhorario` INT(11) NOT NULL AUTO_INCREMENT,
  `idveterinario` INT(11) NULL DEFAULT NULL,
  `idproductoservicio` INT(11) NULL DEFAULT NULL,
  `dia` VARCHAR(9) NULL DEFAULT NULL,
  `horarioinicio` INT(11) NULL DEFAULT NULL,
  `horariofin` INT(11) NULL DEFAULT NULL,
  `estado` CHAR(1) NULL DEFAULT NULL,
  `veterinario_idveterinario` INT(11) NOT NULL,
  PRIMARY KEY (`idhorario`),
  INDEX `idveterinario` (`idveterinario` ASC) VISIBLE,
  INDEX `idproductoservicio` (`idproductoservicio` ASC) VISIBLE,
  INDEX `fk_horario_veterinario1_idx` (`veterinario_idveterinario` ASC) VISIBLE,
  CONSTRAINT `fk_horario_veterinario1`
    FOREIGN KEY (`veterinario_idveterinario`)
    REFERENCES `petcare`.`veterinario` (`idveterinario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `petcare`.`especie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petcare`.`especie` (
  `idespecie` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(15) NULL DEFAULT NULL,
  `estado` CHAR(1) NULL DEFAULT NULL,
  PRIMARY KEY (`idespecie`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `petcare`.`raza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petcare`.`raza` (
  `idraza` INT(11) NOT NULL AUTO_INCREMENT,
  `idespecie` INT(11) NULL DEFAULT NULL,
  `nombre` VARCHAR(20) NULL DEFAULT NULL,
  `estado` CHAR(1) NULL DEFAULT NULL,
  `especie_idespecie` INT(11) NOT NULL,
  PRIMARY KEY (`idraza`),
  INDEX `idespecie` (`idespecie` ASC) VISIBLE,
  INDEX `fk_raza_especie1_idx` (`especie_idespecie` ASC) VISIBLE,
  CONSTRAINT `fk_raza_especie1`
    FOREIGN KEY (`especie_idespecie`)
    REFERENCES `petcare`.`especie` (`idespecie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `petcare`.`mascota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petcare`.`mascota` (
  `idmascota` INT(11) NOT NULL AUTO_INCREMENT,
  `idcliente` INT(11) NULL DEFAULT NULL,
  `idraza` INT(11) NULL DEFAULT NULL,
  `nombre` VARCHAR(35) NULL DEFAULT NULL,
  `fechaNac` DATE NULL DEFAULT NULL,
  `peso` DECIMAL(4,2) NULL DEFAULT NULL,
  `color` VARCHAR(17) NULL DEFAULT NULL,
  `fotoPerfil` VARCHAR(100) NULL DEFAULT NULL,
  `esterilizado` CHAR(2) NULL DEFAULT NULL,
  `etapa` VARCHAR(15) NULL DEFAULT NULL,
  `fechaRegistro` DATE NULL DEFAULT CURRENT_TIMESTAMP(),
  `estado` CHAR(1) NULL DEFAULT NULL,
  `cliente_idcliente` INT(11) NOT NULL,
  PRIMARY KEY (`idmascota`),
  INDEX `idcliente` (`idcliente` ASC) VISIBLE,
  INDEX `idraza` (`idraza` ASC) VISIBLE,
  INDEX `fk_mascota_cliente1_idx` (`cliente_idcliente` ASC) VISIBLE,
  CONSTRAINT `mascota_ibfk_1`
    FOREIGN KEY (`idraza`)
    REFERENCES `petcare`.`raza` (`idraza`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_mascota_cliente1`
    FOREIGN KEY (`cliente_idcliente`)
    REFERENCES `petcare`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `petcare`.`cita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petcare`.`cita` (
  `idcita` INT(11) NOT NULL AUTO_INCREMENT,
  `idcliente` INT(11) NULL DEFAULT NULL,
  `idmascota` INT(11) NULL DEFAULT NULL,
  `idhorario` INT(11) NULL DEFAULT NULL,
  `estado` VARCHAR(15) NULL DEFAULT NULL,
  `fechacreacion` DATE NULL DEFAULT CURRENT_TIMESTAMP(),
  `cliente_idcliente` INT(11) NOT NULL,
  `horario_idhorario` INT(11) NOT NULL,
  `mascota_idmascota` INT(11) NOT NULL,
  PRIMARY KEY (`idcita`),
  INDEX `idcliente` (`idcliente` ASC) VISIBLE,
  INDEX `idmascota` (`idmascota` ASC) VISIBLE,
  INDEX `fk_cita_cliente1_idx` (`cliente_idcliente` ASC) VISIBLE,
  INDEX `fk_cita_horario1_idx` (`horario_idhorario` ASC) VISIBLE,
  INDEX `fk_cita_mascota1_idx` (`mascota_idmascota` ASC) VISIBLE,
  CONSTRAINT `fk_cita_cliente1`
    FOREIGN KEY (`cliente_idcliente`)
    REFERENCES `petcare`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cita_horario1`
    FOREIGN KEY (`horario_idhorario`)
    REFERENCES `petcare`.`horario` (`idhorario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cita_mascota1`
    FOREIGN KEY (`mascota_idmascota`)
    REFERENCES `petcare`.`mascota` (`idmascota`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `petcare`.`vacuna`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petcare`.`vacuna` (
  `idvacuna` INT(11) NOT NULL AUTO_INCREMENT,
  `lote` VARCHAR(15) NULL DEFAULT NULL,
  `tipo` VARCHAR(15) NULL DEFAULT NULL,
  PRIMARY KEY (`idvacuna`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `petcare`.`detallevacuna`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petcare`.`detallevacuna` (
  `iddetallevacuna` INT(11) NOT NULL,
  `idmascota` INT(11) NULL DEFAULT NULL,
  `idvacuna` INT(11) NULL DEFAULT NULL,
  `idveterinario` INT(11) NULL DEFAULT NULL,
  `fecha` DATE NULL DEFAULT CURRENT_TIMESTAMP(),
  `observacion` VARCHAR(55) NULL DEFAULT NULL,
  `mascota_idmascota` INT(11) NOT NULL,
  PRIMARY KEY (`iddetallevacuna`),
  INDEX `idmascota` (`idmascota` ASC) VISIBLE,
  INDEX `idvacuna` (`idvacuna` ASC) VISIBLE,
  INDEX `idveterinario` (`idveterinario` ASC) VISIBLE,
  INDEX `fk_detallevacuna_mascota1_idx` (`mascota_idmascota` ASC) VISIBLE,
  CONSTRAINT `detallevacuna_ibfk_1`
    FOREIGN KEY (`idvacuna`)
    REFERENCES `petcare`.`vacuna` (`idvacuna`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_detallevacuna_mascota1`
    FOREIGN KEY (`mascota_idmascota`)
    REFERENCES `petcare`.`mascota` (`idmascota`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `petcare`.`venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petcare`.`venta` (
  `idventa` INT(11) NOT NULL AUTO_INCREMENT,
  `idcliente` INT(11) NULL DEFAULT NULL,
  `idveterinario` INT(11) NULL DEFAULT NULL,
  `total` DECIMAL(7,2) NULL DEFAULT NULL,
  `fecha` DATE NULL DEFAULT CURRENT_TIMESTAMP(),
  `estado` CHAR(1) NULL DEFAULT NULL,
  `veterinario_idveterinario` INT(11) NOT NULL,
  `cliente_idcliente` INT(11) NOT NULL,
  PRIMARY KEY (`idventa`),
  INDEX `idcliente` (`idcliente` ASC) VISIBLE,
  INDEX `idveterinario` (`idveterinario` ASC) VISIBLE,
  INDEX `fk_venta_veterinario1_idx` (`veterinario_idveterinario` ASC) VISIBLE,
  INDEX `fk_venta_cliente1_idx` (`cliente_idcliente` ASC) VISIBLE,
  CONSTRAINT `fk_venta_veterinario1`
    FOREIGN KEY (`veterinario_idveterinario`)
    REFERENCES `petcare`.`veterinario` (`idveterinario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venta_cliente1`
    FOREIGN KEY (`cliente_idcliente`)
    REFERENCES `petcare`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `petcare`.`tipoproductoservicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petcare`.`tipoproductoservicio` (
  `idtipoproductoservicio` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(9) NULL DEFAULT NULL,
  `estado` CHAR(1) NULL DEFAULT NULL,
  PRIMARY KEY (`idtipoproductoservicio`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `petcare`.`productoservicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petcare`.`productoservicio` (
  `idproductoservicio` INT(11) NOT NULL AUTO_INCREMENT,
  `idtipoproductoservicio` INT(11) NULL DEFAULT NULL,
  `nombre` VARCHAR(50) NULL DEFAULT NULL,
  `precio` DECIMAL(5,2) NULL DEFAULT NULL,
  `descripcion` VARCHAR(55) NULL DEFAULT NULL,
  `estado` CHAR(1) NULL DEFAULT NULL,
  `tipoproductoservicio_idtipoproductoservicio` INT(11) NOT NULL,
  PRIMARY KEY (`idproductoservicio`),
  INDEX `idtipoproductoservicio` (`idtipoproductoservicio` ASC) VISIBLE,
  INDEX `fk_productoservicio_tipoproductoservicio1_idx` (`tipoproductoservicio_idtipoproductoservicio` ASC) VISIBLE,
  CONSTRAINT `fk_productoservicio_tipoproductoservicio1`
    FOREIGN KEY (`tipoproductoservicio_idtipoproductoservicio`)
    REFERENCES `petcare`.`tipoproductoservicio` (`idtipoproductoservicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `petcare`.`detalleventa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petcare`.`detalleventa` (
  `iddetalleventa` INT(11) NOT NULL AUTO_INCREMENT,
  `idventa` INT(11) NULL DEFAULT NULL,
  `productoservicio` INT(11) NULL DEFAULT NULL,
  `cantidad` INT(11) NULL DEFAULT NULL,
  `importe` DECIMAL(5,2) NULL DEFAULT NULL,
  `venta_idventa` INT(11) NOT NULL,
  `productoservicio_idproductoservicio` INT(11) NOT NULL,
  PRIMARY KEY (`iddetalleventa`),
  INDEX `idventa` (`idventa` ASC) VISIBLE,
  INDEX `fk_detalleventa_venta1_idx` (`venta_idventa` ASC) VISIBLE,
  INDEX `fk_detalleventa_productoservicio1_idx` (`productoservicio_idproductoservicio` ASC) VISIBLE,
  CONSTRAINT `fk_detalleventa_venta1`
    FOREIGN KEY (`venta_idventa`)
    REFERENCES `petcare`.`venta` (`idventa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalleventa_productoservicio1`
    FOREIGN KEY (`productoservicio_idproductoservicio`)
    REFERENCES `petcare`.`productoservicio` (`idproductoservicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
